HFWM_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("food_management.urls")),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

food_management/urls.py
from django.urls import path
from . views import *

urlpatterns = [
    path('', dashboard, name='dashboard'),
    path('base', base, name='base'),
    
    path('add_category/', add_category, name='add_category'),
    path('category_list/', category_list, name='category_list'),
    path('delete_category/<int:pk>/', delete_category, name='delete_category'),

    path('add_food_item/', add_food_item, name='add_food_item'),
    path('food_item_list/', food_item_list, name='food_item_list'),
    path('edit_food_item/<int:pk>/', edit_food_item, name='edit_food_item'),
    path('delete_food_item/<int:pk>/', delete_food_item, name='delete_food_item'),

    path('add_food_bank/', add_food_bank, name='add_food_bank'),
    path('food_bank_list/', food_bank_list, name='food_bank_list'),


    path('generate_barcode/', generate_barcode, name='generate_barcode'),

    path('user_login/', user_login, name='user_login'),
    path('user_signup/', user_signup, name='user_signup'),
    path('user_logout/', user_logout, name="user_logout"),



]

food_management/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


class FoodCategory(models.Model):
    name = models.CharField(max_length=100)
    pre_expiry_days = models.PositiveIntegerField(default=0)


    def __str__(self):
        return self.name

class FoodItem(models.Model):
    UNIT_CHOICES = [
        ('kg', 'kg'),
        ('g', 'g'),
        ('ml', 'ml'),
        ('pieces', 'pieces'),
        ('packets', 'packets'),
        ('litres', 'litres'),
        ('units', 'units'),
        ('other', 'other'),
    ]    
    category = models.ForeignKey(FoodCategory, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    quantity = models.DecimalField(max_digits=10, decimal_places=2)
    unit = models.CharField(max_length=20, choices=UNIT_CHOICES)
    expiry_date = models.DateField()
    added_by = models.ForeignKey(User, on_delete=models.CASCADE)
    barcode = models.CharField(max_length=100, blank=True, null=True)

    def calculate_expiry_date(self):
        pre_expiry_days = self.category.pre_expiry_days
        return self.expiry_date - timezone.timedelta(days=pre_expiry_days)

    def calculate_expiry_date(self):
        pre_expiry_days = self.category.pre_expiry_days
        return self.expiry_date - timezone.timedelta(days=pre_expiry_days)
    
    def __str__(self):
        return self.name


class FoodBank(models.Model):
    Food_bank_name = models.CharField(max_length=100)
    location = models.CharField(max_length=100)

    def __str__(self):
        return self.name
    

class BarcodeFoodItem(models.Model):
    name = models.CharField(max_length=100)
    expiry_date = models.DateField()
    barcode_image = models.ImageField(upload_to='barcode_images/')

    def __str__(self):
        return self.name

food_management/forms.py
from django import forms
from .models import FoodItem, FoodCategory,FoodBank

class FoodItemForm(forms.ModelForm):
    
    def __init__(self, *args, **kwargs):
        super(FoodItemForm, self).__init__(*args, **kwargs)
        self.fields['category'].queryset = FoodCategory.objects.all()


    

    class Meta:
        model = FoodItem
        fields = ['category', 'name', 'quantity','unit','expiry_date', 'barcode']
        widgets= {
            'expiry_date': forms.DateInput(attrs={'type': 'date'}),
        }


class NewCategoryForm(forms.ModelForm):
    pre_expiry_days = forms.IntegerField(label='Pre-Expiry Days', initial=0) 

    class Meta:
        model = FoodCategory
        fields = ['name', 'pre_expiry_days']


class FoodBankForm(forms.ModelForm):

    
    class Meta:
        model = FoodBank
        fields = ['Food_bank_name', 'location']

food_management/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import FoodItem, FoodCategory
from .forms import FoodItemForm,NewCategoryForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout as auth_logout
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth import login, authenticate
from django.utils import timezone

from barcode.codex import Code128 
from barcode.writer import ImageWriter
import io
from django.core.files.uploadedfile import InMemoryUploadedFile
from .models import BarcodeFoodItem
from django.http import HttpResponse



@login_required(login_url='user_login/')
def dashboard(request):
    total_users = User.objects.count()
    total_food_items = FoodItem.objects.count()
    total_categories = FoodCategory.objects.count()

    approaching_expiry_items = []
    for category in FoodCategory.objects.all():
        pre_expiry_days = category.pre_expiry_days
        approaching_expiry_items.extend(
            FoodItem.objects.filter(
                category=category,
                expiry_date__lte=timezone.now() + timezone.timedelta(days=pre_expiry_days)
            )
        )

    return render(request, 'food_management/dashboard.html', {
        'total_users': total_users,
        'total_food_items': total_food_items,
        'total_categories': total_categories,
        'approaching_expiry_items': approaching_expiry_items
    })


@login_required(login_url='user_login/')
def add_food_item(request):
    if request.method == 'POST':
        form = FoodItemForm(request.POST)
        if form.is_valid():
            category = form.cleaned_data.get('category')
            new_category = form.cleaned_data.get('new_category')

            if not category and new_category:
                category = FoodCategory.objects.create(name=new_category)            
            food_item = form.save(commit=False)
            food_item.added_by = request.user
            food_item.category = category
            food_item.save()
            return render(request, 'food_management/add_food_item.html', {'form': form})                   
    else:
        form = FoodItemForm()
    return render(request, 'food_management/add_food_item.html', {'form': form})


@login_required(login_url='user_login/')
def food_item_list(request):
    food_items = FoodItem.objects.filter(added_by=request.user)
    return render(request, 'food_management/food_item_list.html', {'food_items': food_items})



@login_required(login_url='user_login/')
def edit_food_item(request, pk):
    food_item = get_object_or_404(FoodItem, pk=pk)
    if request.method == 'POST':
        form = FoodItemForm(request.POST, instance=food_item)
        if form.is_valid():
            form.save()
            return redirect('food_item_list')
    else:
        form = FoodItemForm(instance=food_item)
    return render(request, 'food_management/edit_food_item.html', {'form': form})



@login_required(login_url='user_login/')
def delete_food_item(request, pk):
    food_item = get_object_or_404(FoodItem, pk=pk)
    if request.method == 'POST':
        food_item.delete()
        return redirect('food_item_list')
    return render(request, 'food_management/delete_food_item_confirm.html', {'food_item': food_item})


@login_required(login_url='user_login/')
def add_category(request):
    if request.method == 'POST':
        form = NewCategoryForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('add_food_item')
    else:
        form = NewCategoryForm()
    return render(request, 'food_management/add_category.html', {'form': form})




@login_required(login_url='user_login/')
def category_list(request):
    categories = FoodCategory.objects.all()
    pre_expiry_days = FoodCategory.objects.all()
    return render(request, 'food_management/category_list.html', {'categories': categories, 'pre_expiry_days': pre_expiry_days})





@login_required(login_url='user_login/')
def delete_category(request, pk):
     category = get_object_or_404(FoodCategory, pk=pk)
     if request.method == 'POST':
         category.delete()
         return redirect('add_food_item') 
     return render(request, 'food_management/delete_category_confirm.html', {'category': category})


from .forms import FoodBankForm
from .models import FoodBank

@login_required(login_url='user_login/')
def add_food_bank(request):
    if request.method == 'POST':
        form = FoodBankForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('add_food_bank')
    else:
        form = FoodBankForm()
    return render(request, 'food_management/add_food_bank.html', {'form': form})


def food_bank_list(request):
    food_banks = FoodBank.objects.all()
    return render(request, 'food_management/food_bank_list.html', {'food_banks': food_banks})




def user_signup(request):
    if request.user.is_authenticated:
        return redirect('/')
    if request.method == 'POST':
        first_name = request.POST.get('First_Name')
        last_name = request.POST.get('Last_Name')
        email = request.POST.get('Email')
        password = request.POST.get('Password')
        confirm_password = request.POST.get('Confirm_Password')

        if password != confirm_password:
            messages.error(request, 'Passwords do not match')
            return redirect('user_signup')
        

        user = User.objects.create_user(
            username=email,
            first_name=first_name,
            last_name=last_name,
            email=email,
            password=password,
        )


        messages.success(request, 'Account created successfully')
        return redirect('user_login') 
    
    return render(request, 'auth/user_signup.html')



def user_login(request):
    if request.user.is_authenticated:
        return redirect('/')
    if request.method == 'POST':
        email = request.POST['Email']
        password = request.POST['Password']
        user = authenticate(request, username=email, password=password)
        
        if user is not None and not user.is_superuser:
            login(request, user)
            messages.success(request, 'Login successful.')
            return redirect('/')
        else:
            messages.error(request, 'Invalid login credentials.')

    return render(request, 'auth/user_login.html')

@login_required(login_url='user_login/')
def user_logout(request):
    auth_logout(request)
    messages.success(request, 'Logged out successfully')
    return redirect('user_login')



@login_required(login_url='user_login/')
def base(request):
    return render(request, 'base.html')



from django.core.exceptions import ValidationError
from django.core.files.base import ContentFile


def generate_barcode_image(content):
    try:
        buffer = io.BytesIO()
        code = Code128(content, writer=ImageWriter())
        code.save(buffer)

        # Create a ContentFile with a proper filename
        filename = f'{content}.png'
        barcode_image = ContentFile(buffer.getvalue(), name=filename)

        return barcode_image
    except Exception as e:
        print(f"Error generating barcode image: {e}")
        raise ValidationError("Error generating barcode image.")


@login_required(login_url='user_login/')
def generate_barcode(request):
    if request.method == 'POST':
        name = request.POST['name']
        expiry_date = request.POST['expiry_date']
        
        food_item = BarcodeFoodItem.objects.create(name=name, expiry_date=expiry_date)
        barcode_image = generate_barcode_image(f'{food_item.id}-{food_item.name}')
        food_item.barcode_image.save(f'{food_item.id}.png', barcode_image)

        return HttpResponse('Barcode successfully generated!')

    return render(request, 'food_management/generate_barcode.html')

templates/food_management/add_category.html
{% extends 'base.html' %}
{% block title %}Add Category{% endblock %}

{% block content %}
    <h1>Add Category</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Add Category</button>
    </form>
{% endblock %}

templates/food_management/add_food_bank.html
{% extends 'base.html' %}
{% block title %}Add Food Bank{% endblock %}

{% block content %}

    <h1>Add Food Bank</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>

{% endblock %}

templates/food_management/add_food_item.html
{% extends 'base.html' %}
{% block title %}Add Food{% endblock %}

{% block content %}

<h1>Add Food Item</h1>

<!-- Form for adding food item -->
<form id="foodItemForm" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
</form> 

<!-- Link to add a new category -->
<p>Didn't find your category? <a href="{% url 'add_category' %}">Click to Add</a></p>
<!-- Link to delete categories -->
<p>Want to delete your category? <a href="{% url 'category_list' %}">Click to Delete</a></p>

<!-- Barcode scanning section -->
<h2>Barcode Scanner</h2>
<button id="scanButton">Scan Barcode</button>

<!-- Script for barcode scanning -->
<script src="https://cdn.jsdelivr.net/npm/quagga/dist/quagga.min.js"></script>
<script>
    // Initialize QuaggaJS
    Quagga.init({
        inputStream: {
            name: "Live",
            type: "LiveStream",
            target: document.querySelector('#foodItemForm')
        },
        decoder: {
            readers: ['ean_reader']
        }
    }, function(err) {
        if (err) {
            console.error('Failed to initialize Quagga:', err);
            return;
        }
        console.log('Quagga initialized successfully.');
        Quagga.start();
    });

    // Handle barcode scanning results
    Quagga.onDetected(function(result) {
        var barcode = result.codeResult.code;
        console.log('Barcode detected:', barcode);
        // Here, you can perform actions with the scanned barcode, such as populating form fields
        // For simplicity, let's just display an alert with the scanned barcode
        alert('Scanned Barcode: ' + barcode);
    });

    // Stop Quagga when leaving the page
    window.addEventListener('beforeunload', function() {
        Quagga.stop();
    });
</script>

</div>

{% endblock %}

templates/food_management/category_list.html
{% extends 'base.html' %}
{% block title %}categories List{% endblock %}

{% block content %}
    <h1>Categories List</h1>
    <ul>
        {% for category in categories %}
            <li>
                {{ category.name }}
                {{category.pre_expiry_days}}
                <a href="{% url 'delete_category' pk=category.pk %}">Delete</a>
            </li>
        {% endfor %}
    </ul>

{% endblock %}

templates/food_management/dashboard.html
{% extends 'base.html' %}
{% block title %}Dashboard{% endblock %}

{% block content %}
    <div class="card" style="background-color: #ff9999;">
        <h2>Total Users</h2>
        <p>{{ total_users }}</p>
    </div>
    <div class="card" style="background-color: #99ff99;">
        <h2>Total Food Items Added</h2>
        <p>{{ total_food_items }}</p>
    </div>
    <div class="card" style="background-color: #9999ff;">
        <h2>Total Categories</h2>
        <p>{{ total_categories }}</p>
    </div>
</div>


<div class="dashboard">
    <div class="notification">
        {% if approaching_expiry_items %}
            <p>Your product is about to expire. Please deposit it to the local food bank.</p>
            <ul>
                {% for item in approaching_expiry_items %}
                    <li>{{ item.name }} - Expiry Date: {{ item.expiry_date }}</li>
                {% endfor %}
            </ul>
        {% else %}
            <p>No items approaching expiry date.</p>
        {% endif %}
    </div>
{% endblock %}

templates/food_management/delete_category_confirm.html
{% extends 'base.html' %}
{% block title %}Delete Category{% endblock %}

{% block content %}
<body>
    <h1>Delete Category</h1>
    <p>Are you sure you want to delete the category "{{ category.name }}"?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Confirm Delete</button>
    </form>
{% endblock %}

templates/food_management/delete_food_item_confirm.html
{% extends 'base.html' %}
{% block title %}Delete Item List{% endblock %}

{% block content %}
    <h1>Delete Food Item</h1>
    <p>Are you sure you want to delete "{{ food_item.name }}"?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Confirm Delete</button>
    </form>
{% endblock %}

templates/food_management/edit_food_item.html
{% extends 'base.html' %}
{% block title %}Edit Food Item{% endblock %}

{% block content %}
    <h1>Edit Food Item</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save Changes</button>
    </form>
{% endblock %}

templates/food_management/food_bank_list.html
{% extends 'base.html' %}
{% block title %}Food Bank List{% endblock %}

{% block content %}
    <h1>Food Bank List</h1>
    <ul>
        <p>Didn't find Local Food bank? <a href="{% url 'add_food_bank' %}">Click to Add</a></p>
        {% for food_bank in food_banks %}
            <li>
                {{ food_bank.Food_bank_name }}
                {{food_bank.location}}

               
            </li>
        {% endfor %}
    </ul>

{% endblock %}

templates/food_management/food_item_list.html
{% extends 'base.html' %}
{% block title %}Food Item List{% endblock %}

{% block content %}
<body>
    <h1>Food Item List</h1>
    <ul>
        {% for food_item in food_items %}
            <li>{{ forloop.counter }}. {{ food_item.name }} - {{ food_item.quantity }} {{ food_item.get_unit_display }}
                <a href="{% url 'edit_food_item' pk=food_item.pk %}">Edit</a>
                <a href="{% url 'delete_food_item' pk=food_item.pk %}">Delete</a>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

templates/food_management/generate_barcode.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BarCode Generation</title>
</head>
<body>
    <h2>BarCode Generation</h2>
    <form method="post" action="{% url 'generate_barcode' %}">
        {% csrf_token %}
        <label for="name">Name:</label>
        <input type="text" id="name" name="name" required><br>

        <label for="expiry_date">Expiry Date:</label>
        <input type="date" id="expiry_date" name="expiry_date" required><br>

        <button type="submit">BarCode Generation</button>
    </form>
</body>
</html>